// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixG6uo3eZ_s2CmJSYHmISqFFH8VHcWcU',
    appId: '1:249169509260:web:0372eff57a7353e55e34a9',
    messagingSenderId: '249169509260',
    projectId: 'leaning-helper',
    authDomain: 'leaning-helper.firebaseapp.com',
    storageBucket: 'leaning-helper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhUPnGoDeY9HFPzqFAQSXMIPVZ0dLCt_I',
    appId: '1:249169509260:android:f59c91a15c920fb35e34a9',
    messagingSenderId: '249169509260',
    projectId: 'leaning-helper',
    storageBucket: 'leaning-helper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxEhRof0Mh3PAplP-owYoYzJ3btH3mp4',
    appId: '1:249169509260:ios:2d467a8124814aef5e34a9',
    messagingSenderId: '249169509260',
    projectId: 'leaning-helper',
    storageBucket: 'leaning-helper.firebasestorage.app',
    iosBundleId: 'com.example.learningHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHxEhRof0Mh3PAplP-owYoYzJ3btH3mp4',
    appId: '1:249169509260:ios:2d467a8124814aef5e34a9',
    messagingSenderId: '249169509260',
    projectId: 'leaning-helper',
    storageBucket: 'leaning-helper.firebasestorage.app',
    iosBundleId: 'com.example.learningHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAixG6uo3eZ_s2CmJSYHmISqFFH8VHcWcU',
    appId: '1:249169509260:web:cafaf27384543fc25e34a9',
    messagingSenderId: '249169509260',
    projectId: 'leaning-helper',
    authDomain: 'leaning-helper.firebaseapp.com',
    storageBucket: 'leaning-helper.firebasestorage.app',
  );
}
